<?
require($_SERVER["DOCUMENT_ROOT"]."/bitrix/header.php");
$APPLICATION->SetTitle("Title");
?><?$APPLICATION->IncludeComponent(
	"flight",
	"",
	Array(
	)
);?><br>
<br>
<br>
<br>
<br><?require($_SERVER["DOCUMENT_ROOT"]."/bitrix/footer.php");?>